name: github-linux

env:
  xsdk-repo: xsdk-project/spack-xsdk
  xsdk-branch: xsdk-0.6.0 #develop


# Controls when the action will run
on:
  # trigger the workflow manually
  workflow_dispatch:
  # # trigger the workflow on schedule
  # # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
  # schedule:
  #   - cron:  '* * * * *'



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  #############################################################################
  #############################################################################
  # GitHub-hosted runners

  github-ubuntu:
    runs-on: ${{ matrix.runner }}
    continue-on-error: false
    strategy:
      matrix:
        runner: [ubuntu-latest]
        compiler: [gcc]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ env.xsdk-repo }}
          ref: ${{ env.xsdk-branch }}
      - uses: vreshniak/xsdk-ci-test@master
        with:
          cmd: echo Hello World
          # cmd: './bin/spack install xsdk%${{ matrix.compiler }}'